"""add_quiz_questions_and_attempts

Revision ID: 29c3d4e0dd46
Revises: 34e4fbd70075
Create Date: 2026-03-28 19:21:11.358773

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

JSON = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")
TEXT_ARRAY = sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), "postgresql")

# revision identifiers, used by Alembic.
revision: str = "29c3d4e0dd46"
down_revision: Union[str, None] = "34e4fbd70075"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quiz_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column(
            "answers",
            JSON,
            nullable=False,
            comment="Map of question_id -> selected_option_index",
        ),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("percentage", sa.Float(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_quiz_attempts_user_lesson", "quiz_attempts", ["user_id", "lesson_id"], unique=False
    )
    op.create_table(
        "quiz_questions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("lesson_id", sa.Uuid(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("options", TEXT_ARRAY, nullable=False),
        sa.Column("correct_option", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["lesson_id"], ["lessons.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_quiz_questions_lesson_id", "quiz_questions", ["lesson_id"], unique=False)
    with op.batch_alter_table("certificates") as batch_op:
        batch_op.drop_constraint(op.f("uq_certificate_user_course"), type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("certificates") as batch_op:
        batch_op.create_unique_constraint(
            op.f("uq_certificate_user_course"),
            ["user_id", "course_id"],
            postgresql_nulls_not_distinct=False,
        )
    op.drop_index("idx_quiz_questions_lesson_id", table_name="quiz_questions")
    op.drop_table("quiz_questions")
    op.drop_index("idx_quiz_attempts_user_lesson", table_name="quiz_attempts")
    op.drop_table("quiz_attempts")
    # ### end Alembic commands ###
