"""add_is_public_and_course_ratings

Revision ID: 34e4fbd70075
Revises: a4fd9591e218
Create Date: 2026-03-28 16:38:52.529758

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "34e4fbd70075"
down_revision: Union[str, None] = "a4fd9591e218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_ratings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("course_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("review", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["course_id"], ["courses.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "course_id", name="uq_user_course_rating"),
    )
    op.create_index("idx_ratings_course_id", "course_ratings", ["course_id"], unique=False)
    op.create_index("idx_ratings_user_id", "course_ratings", ["user_id"], unique=False)
    op.add_column(
        "courses",
        sa.Column("is_public", sa.Boolean(), nullable=False, server_default=sa.text("false")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("courses", "is_public")
    op.drop_index("idx_ratings_user_id", table_name="course_ratings")
    op.drop_index("idx_ratings_course_id", table_name="course_ratings")
    op.drop_table("course_ratings")
    # ### end Alembic commands ###
