"""add cover_image_url and social_links to user

Revision ID: 6ec9fa3e41bf
Revises: f99f9abbc335
Create Date: 2026-03-29 02:06:15.816747

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

JSON = sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql")

# revision identifiers, used by Alembic.
revision: str = "6ec9fa3e41bf"
down_revision: Union[str, None] = "f99f9abbc335"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "social_links",
            JSON,
            server_default="[]",
            nullable=True,
        ),
    )
    op.execute("UPDATE users SET social_links = '[]' WHERE social_links IS NULL")
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column("social_links", nullable=False)
    op.add_column("users", sa.Column("cover_image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "cover_image_url")
    op.drop_column("users", "social_links")
    # ### end Alembic commands ###
