"""add_auto_play_next_to_users

Revision ID: a6df7f842838
Revises: a1c2b3d4e5f6
Create Date: 2026-04-03 23:48:14.927119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a6df7f842838"
down_revision: Union[str, None] = "a1c2b3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("auto_play_next", sa.Boolean(), nullable=False, server_default=sa.text("true")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auto_play_next")
    # ### end Alembic commands ###
