"""add user profile fields bio tags public

Revision ID: f99f9abbc335
Revises: 29c3d4e0dd46
Create Date: 2026-03-29 00:28:44.525946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f99f9abbc335'
down_revision: Union[str, None] = '29c3d4e0dd46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('profile_tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    op.execute("UPDATE users SET profile_tags = '[]' WHERE profile_tags IS NULL")
    op.alter_column('users', 'profile_tags', nullable=False)
    op.add_column('users', sa.Column('is_profile_public', sa.Boolean(), server_default='false', nullable=True))
    op.execute("UPDATE users SET is_profile_public = false WHERE is_profile_public IS NULL")
    op.alter_column('users', 'is_profile_public', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_profile_public')
    op.drop_column('users', 'profile_tags')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
