"""add production assets and manifests

Revision ID: n2o3p4q5r6s7
Revises: m1n2o3p4q5r6
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "n2o3p4q5r6s7"; down_revision = "m1n2o3p4q5r6"; branch_labels = None; depends_on = None
JSON = sa.JSON().with_variant(postgresql.JSONB(), "postgresql")
UUID = sa.Uuid()

def upgrade() -> None:
    op.create_table("production_assets", sa.Column("id", UUID, primary_key=True), sa.Column("user_id", UUID, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("kind", sa.String(32), nullable=False), sa.Column("source", sa.String(32), nullable=False), sa.Column("state", sa.String(32), nullable=False), sa.Column("display_name", sa.String(255), nullable=False), sa.Column("checksum", sa.String(64)), sa.Column("license", sa.String(255)), sa.Column("tags", JSON, nullable=False), sa.Column("provenance", JSON, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("deleted_at", sa.DateTime(timezone=True)))
    op.create_index("idx_production_assets_owner_state", "production_assets", ["user_id", "state"]); op.create_index("idx_production_assets_checksum", "production_assets", ["user_id", "checksum"])
    op.create_table("production_asset_versions", sa.Column("id", UUID, primary_key=True), sa.Column("asset_id", UUID, sa.ForeignKey("production_assets.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", UUID, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("version", sa.Integer, nullable=False), sa.Column("object_key", sa.String(512), nullable=False, unique=True), sa.Column("checksum", sa.String(64), nullable=False), sa.Column("byte_size", sa.Integer, nullable=False), sa.Column("media_type", sa.String(127), nullable=False), sa.Column("metadata", JSON, nullable=False), sa.Column("provenance", JSON, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("asset_id", "version", name="uq_production_asset_version"), sa.UniqueConstraint("user_id", "checksum", name="uq_production_asset_owner_checksum"))
    op.create_index("idx_production_asset_versions_asset", "production_asset_versions", ["asset_id"])
    op.create_table("production_asset_upload_intents", sa.Column("id", UUID, primary_key=True), sa.Column("asset_id", UUID, sa.ForeignKey("production_assets.id", ondelete="CASCADE"), nullable=False), sa.Column("user_id", UUID, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("object_key", sa.String(512), nullable=False, unique=True), sa.Column("expected_size", sa.Integer, nullable=False), sa.Column("expected_media_type", sa.String(127), nullable=False), sa.Column("expected_checksum", sa.String(64)), sa.Column("upload_id", sa.String(64), nullable=False, unique=True), sa.Column("status", sa.String(24), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False))
    op.create_index("idx_production_asset_intents_owner_expiry", "production_asset_upload_intents", ["user_id", "expires_at"])
    op.create_table("production_asset_bindings", sa.Column("id", UUID, primary_key=True), sa.Column("spec_version_id", UUID, sa.ForeignKey("production_spec_versions.id", ondelete="CASCADE"), nullable=False), sa.Column("asset_id", UUID, sa.ForeignKey("production_assets.id", ondelete="RESTRICT"), nullable=False), sa.Column("asset_version_id", UUID, sa.ForeignKey("production_asset_versions.id", ondelete="RESTRICT"), nullable=False), sa.Column("asset_request_id", sa.String(100), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("spec_version_id", "asset_request_id", name="uq_production_asset_binding_request"))
    op.create_table("provider_credentials", sa.Column("id", UUID, primary_key=True), sa.Column("user_id", UUID, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("provider", sa.String(80), nullable=False), sa.Column("credential_kind", sa.String(40), nullable=False), sa.Column("label", sa.String(100), nullable=False), sa.Column("encrypted_secret", sa.Text, nullable=False), sa.Column("key_version", sa.Integer, nullable=False), sa.Column("masked_hint", sa.String(24), nullable=False), sa.Column("active", sa.Boolean, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("user_id", "provider", "credential_kind", "label", name="uq_provider_credential_label"))
    op.create_table("budget_reservations", sa.Column("id", UUID, primary_key=True), sa.Column("user_id", UUID, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("run_id", UUID, sa.ForeignKey("production_runs.id", ondelete="SET NULL")), sa.Column("kind", sa.String(80), nullable=False), sa.Column("reserved_cost", sa.Numeric(18,6), nullable=False), sa.Column("actual_cost", sa.Numeric(18,6)), sa.Column("status", sa.String(20), nullable=False), sa.Column("metadata", JSON, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)))
    op.create_index("idx_budget_reservations_owner_status", "budget_reservations", ["user_id", "status"])
    op.create_table("render_manifests", sa.Column("id", UUID, primary_key=True), sa.Column("user_id", UUID, sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False), sa.Column("spec_version_id", UUID, sa.ForeignKey("production_spec_versions.id", ondelete="CASCADE"), nullable=False), sa.Column("input_checksum", sa.String(64), nullable=False), sa.Column("manifest", JSON, nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False), sa.UniqueConstraint("user_id", "input_checksum", name="uq_render_manifest_owner_input"))

def downgrade() -> None:
    for table in ("render_manifests", "budget_reservations", "provider_credentials", "production_asset_bindings", "production_asset_upload_intents", "production_asset_versions", "production_assets"): op.drop_table(table)
